# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CarParkingManager(object):
    def setupUi(self, CarParkingManager):
        CarParkingManager.setObjectName("CarParkingManager")
        CarParkingManager.resize(922, 379)
        CarParkingManager.setMinimumSize(QtCore.QSize(922, 379))
        CarParkingManager.setMaximumSize(QtCore.QSize(922, 379))
        self.centralwidget = QtWidgets.QWidget(CarParkingManager)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-100, -230, 1021, 611))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(30, 30, 36);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.s1 = QtWidgets.QPushButton(self.frame)
        self.s1.setGeometry(QtCore.QRect(520, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s1.setFont(font)
        self.s1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s1.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s1.setCheckable(False)
        self.s1.setObjectName("s1")
        self.s2 = QtWidgets.QPushButton(self.frame)
        self.s2.setGeometry(QtCore.QRect(640, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s2.setFont(font)
        self.s2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s2.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s2.setCheckable(False)
        self.s2.setObjectName("s2")
        self.s15 = QtWidgets.QPushButton(self.frame)
        self.s15.setGeometry(QtCore.QRect(760, 550, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s15.setFont(font)
        self.s15.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s15.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s15.setCheckable(False)
        self.s15.setObjectName("s15")
        self.s4 = QtWidgets.QPushButton(self.frame)
        self.s4.setGeometry(QtCore.QRect(880, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s4.setFont(font)
        self.s4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s4.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s4.setCheckable(False)
        self.s4.setObjectName("s4")
        self.s5 = QtWidgets.QPushButton(self.frame)
        self.s5.setGeometry(QtCore.QRect(520, 430, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s5.setFont(font)
        self.s5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s5.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s5.setCheckable(False)
        self.s5.setObjectName("s5")
        self.s11 = QtWidgets.QPushButton(self.frame)
        self.s11.setGeometry(QtCore.QRect(760, 490, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s11.setFont(font)
        self.s11.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s11.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s11.setCheckable(False)
        self.s11.setObjectName("s11")
        self.s13 = QtWidgets.QPushButton(self.frame)
        self.s13.setGeometry(QtCore.QRect(520, 550, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s13.setFont(font)
        self.s13.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s13.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s13.setCheckable(False)
        self.s13.setObjectName("s13")
        self.s8 = QtWidgets.QPushButton(self.frame)
        self.s8.setGeometry(QtCore.QRect(880, 430, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s8.setFont(font)
        self.s8.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s8.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s8.setCheckable(False)
        self.s8.setObjectName("s8")
        self.s6 = QtWidgets.QPushButton(self.frame)
        self.s6.setGeometry(QtCore.QRect(640, 430, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s6.setFont(font)
        self.s6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s6.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s6.setCheckable(False)
        self.s6.setObjectName("s6")
        self.s10 = QtWidgets.QPushButton(self.frame)
        self.s10.setGeometry(QtCore.QRect(640, 490, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s10.setFont(font)
        self.s10.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s10.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s10.setCheckable(False)
        self.s10.setObjectName("s10")
        self.s3 = QtWidgets.QPushButton(self.frame)
        self.s3.setGeometry(QtCore.QRect(760, 370, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s3.setFont(font)
        self.s3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s3.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s3.setCheckable(False)
        self.s3.setObjectName("s3")
        self.s7 = QtWidgets.QPushButton(self.frame)
        self.s7.setGeometry(QtCore.QRect(760, 430, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s7.setFont(font)
        self.s7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s7.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s7.setCheckable(False)
        self.s7.setObjectName("s7")
        self.s16 = QtWidgets.QPushButton(self.frame)
        self.s16.setGeometry(QtCore.QRect(880, 550, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s16.setFont(font)
        self.s16.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s16.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s16.setCheckable(False)
        self.s16.setObjectName("s16")
        self.s14 = QtWidgets.QPushButton(self.frame)
        self.s14.setGeometry(QtCore.QRect(640, 550, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s14.setFont(font)
        self.s14.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s14.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s14.setCheckable(False)
        self.s14.setObjectName("s14")
        self.s9 = QtWidgets.QPushButton(self.frame)
        self.s9.setGeometry(QtCore.QRect(520, 490, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s9.setFont(font)
        self.s9.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s9.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s9.setCheckable(False)
        self.s9.setObjectName("s9")
        self.s12 = QtWidgets.QPushButton(self.frame)
        self.s12.setGeometry(QtCore.QRect(880, 490, 111, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaRounded LT Std BdCn")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.s12.setFont(font)
        self.s12.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.s12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.s12.setStyleSheet("\n"
"background-color: rgb(64, 255, 80);\n"
"color: rgb(0,0,0);\n"
"\n"
"\n"
"")
        self.s12.setCheckable(False)
        self.s12.setObjectName("s12")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 260, 921, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgba(255, 255, 255, 225);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(180, 390, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius: 15px;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.ENTRYBUTTON = QtWidgets.QPushButton(self.frame)
        self.ENTRYBUTTON.setGeometry(QtCore.QRect(190, 460, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.ENTRYBUTTON.setFont(font)
        self.ENTRYBUTTON.setStyleSheet("background-color: rgb(255, 155, 113);\n"
"border-radius: 20px;\n"
"color: rgba(0, 0, 0, 200);\n"
"\n"
"QPushButton{\n"
"background-color: rgba(255, 155, 113,50);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgba(255, 155, 113,25);\n"
"}\n"
"")
        self.ENTRYBUTTON.setObjectName("ENTRYBUTTON")
        self.EXITBUTTON = QtWidgets.QPushButton(self.frame)
        self.EXITBUTTON.setGeometry(QtCore.QRect(310, 460, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.EXITBUTTON.setFont(font)
        self.EXITBUTTON.setStyleSheet("background-color: rgb(255, 155, 113);\n"
"border-radius: 20px;\n"
"color: rgba(0, 0, 0, 200);")
        self.EXITBUTTON.setObjectName("EXITBUTTON")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(130, 510, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgba(255, 255, 255, 225);")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        CarParkingManager.setCentralWidget(self.centralwidget)

        self.retranslateUi(CarParkingManager)
        QtCore.QMetaObject.connectSlotsByName(CarParkingManager)

    def retranslateUi(self, CarParkingManager):
        _translate = QtCore.QCoreApplication.translate
        CarParkingManager.setWindowTitle(_translate("CarParkingManager", "Car Parking Manager"))
        self.s1.setText(_translate("CarParkingManager", "1"))
        self.s2.setText(_translate("CarParkingManager", "2"))
        self.s15.setText(_translate("CarParkingManager", "15"))
        self.s4.setText(_translate("CarParkingManager", "4"))
        self.s5.setText(_translate("CarParkingManager", "5"))
        self.s11.setText(_translate("CarParkingManager", "11"))
        self.s13.setText(_translate("CarParkingManager", "13"))
        self.s8.setText(_translate("CarParkingManager", "8"))
        self.s6.setText(_translate("CarParkingManager", "6"))
        self.s10.setText(_translate("CarParkingManager", "10"))
        self.s3.setText(_translate("CarParkingManager", "3"))
        self.s7.setText(_translate("CarParkingManager", "7"))
        self.s16.setText(_translate("CarParkingManager", "16"))
        self.s14.setText(_translate("CarParkingManager", "14"))
        self.s9.setText(_translate("CarParkingManager", "9"))
        self.s12.setText(_translate("CarParkingManager", "12"))
        self.label.setText(_translate("CarParkingManager", "CAR PARKING MANAGEMENT"))
        self.lineEdit.setPlaceholderText(_translate("CarParkingManager", "Vehicle Number"))
        self.ENTRYBUTTON.setText(_translate("CarParkingManager", "Entry"))
        self.EXITBUTTON.setText(_translate("CarParkingManager", "Exit"))
